# Python Packages: NumPy

## Numpy

Python does not know how to perfrom calculations using lists. Calculations can be done with the aid of Numeric Python (NumPy)

#### Creating an array

In [13]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(np_baseball)
print(type(np_baseball))

[180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>


In [1]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

print(height)
print(weight)

[1.73, 1.68, 1.71, 1.89, 1.79]
[65.4, 59.2, 63.6, 88.4, 68.7]


In [3]:
# to import numpy
import numpy as np
np_height = np.array(height)
print(np_height)

np_weight = np.array(weight)
print(np_weight)


[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [4]:
# to try out a calculation to find the bmi 
bmi = np_weight / np_height**2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

#### Numpy Subsetting

In [8]:
#you can perfrom the same index selection similar to that of python lists
print(bmi[0])
print(bmi[-1].round(2))

21.85171572722109
21.44


In [11]:
# you can perfrom some logical operations to your subsetting
print(bmi>23)

#to filter the selection, we use
bmi[bmi>23]

[False False False  True False]


array([24.7473475])

In [17]:
#filering with more than one conditions
print(bmi[(bmi > 21) & (bmi <= 23)])

#you can save your filtering condition in a variable
mask = (bmi > 20) & (bmi <= 22)
print(bmi[mask])

[21.85171573 21.75028214 21.44127836]
[21.85171573 20.97505669 21.75028214 21.44127836]


#### 2D NumPy Arrays

In [19]:
#the type of numpy arrays are ususally numpy.ndarray. nd means n number of dimensions
import numpy as np
#example of a 2D array
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 89.2, 63.6, 88.4, 68.2]])
#to find the shape of your array in (x, y) where is number of rows and y is number of columns 
np_2d.shape
#you use the shape to determine the structure of your array

(2, 5)

In [23]:
#to select elements of the 2D array, you can use double []
print(np_2d[0][2])
print(np_2d[1][3])

#or you can use a single [] but separated by a comma
print(np_2d[0, 2])
print(np_2d[1, 3])

# to select a range of cell from both first and second row
print(np_2d[:, 1:3]) #fetching the second and third element form both rows
print(np_2d[1, :])


1.71
88.4
1.71
88.4
[[ 1.68  1.71]
 [89.2  63.6 ]]
[65.4 89.2 63.6 88.4 68.2]


In [25]:
# performing claculations using 2D arrays
bmi_1 = np_2d[1] / np_2d[0]**2
print(bmi_1)

[21.85171573 31.60430839 21.75028214 24.7473475  21.2852283 ]


In [43]:
# Assessment
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


### NumPy Basic Statistics

There are some functions we can use to perform some statistics on numpy arrays such as mean, median, correlation coefficient, standard deviation etc.

In [28]:
# let us generate random values for the height and weight of baseball players
# Arguments for np.random.normal
# distribution mean
# distribution standard deviation
# number of samples
height_1 = np.round(np.random.normal(1.75, 0.20, 5000), 2) 
weight_1 = np.round(np.random.normal(60.32, 15, 5000), 2)

#to combine the height and weight to form an array 
np_baseball = np.column_stack((height_1, weight_1))

print(np_baseball)

[[ 1.66 68.25]
 [ 1.79 72.65]
 [ 1.5  84.27]
 ...
 [ 1.95 91.24]
 [ 2.15 24.13]
 [ 1.61 67.16]]


In [34]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:, 0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:, 0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print("Correlation: " + str(corr))

#print out the sum of height and weight column 
sum_height = np.sum(np_baseball[:, 0])
sum_weight = np.sum(np_baseball[:, 1])
print("The Sum of heights: " + str(sum_height)); print("The Sum of weights: " + str(round(sum_weight, 2)))

Average: 1.751968
Median: 1.75
Standard Deviation: 0.2008279038779223
Correlation: [[ 1.         -0.01184707]
 [-0.01184707  1.        ]]
The Sum of heights: 8759.84
The Sum of weights: 301743.34


In [38]:
import random
import numpy as np

items = ['GK', 'DF', 'MD', 'FW']
positions = []

for i in range(5000):
    positions.append(random.choice(items))

#to check the number of elements to be sure it is 5000 elements 
print(len(positions))

#to convert to an array 
np_positions = np.array(positions)

#to select random heights with mean of 1.75(randomly chosen) and standard deviation of 0.2 
np_heights = np.round(np.random.normal(1.75, 0.2, 5000),2)

5000


In [39]:
# heights and positions have been computed above

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']


# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 1.75
Median height of other players: 1.75


In [ ]:
import os
os.getcwd()